version: '3'

services:
  app:
    build: .
    volumes:
      - $HOME/.gradle:/root/.gradle
      - .:/app
    ports:
    - "8080:8080"
    - "5005:5005"
    environment:
      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,address=5005,server=y,suspend=n